services:
  gateway:
    build: ./gateway
    ports:
      - "6000:6000"
    depends_on:
      - auth-service
      - order-service
      - redis

  auth-service:
    build: ./services/auth-service
    ports:
      - "4001:4001"

  order-service:
    build: ./services/order-service
    ports:
      - "4002:4002"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
